### Soru XXX
Örnek olarak verilen example.txt dosyasını

- Read
- Append
- Write

modlarında açınız.

In [1]:
f = open("example.txt", "r")
print(f.read())
f.close()

merhaba

In [6]:
f = open("example.txt", "w")
f.write("sena")
f.close()

In [8]:

f = open(r"example.txt", "a")
f.write("sena1")
f.close()

In [13]:
f = open("example.txt", "r")
print(f.read())
f.close()

senasezgin

### Soru XXX
Kullanıcıdan ad ve soyad değerlerini alıp, bu değerleri example.txt dosyasına yazdırınız.

In [14]:
name=input("Kullanici adını giriniz")
surname=input("Kullanici soyadini giriniz")
with open("example.txt", "w") as f:
    f.write(name+surname)
f = open("example.txt", "r")
print(f.read())
f.close()

sen sezgin

### Soru XXX
Kullanıcıdan yaş değerini alıp bu değeri example.txt dosyasına, dosyadaki verileri silmeden yazınız.

In [16]:
age = input("yasinizi girin: ")
with open("example.txt","a") as f:
 f.write(age)
 f.close()
 f = open("example.txt", "r")
print(f.read())
f.close()

sen sezgin55

### Soru XXX
example.txt dosyasının ilk 5 satırını okuyup ekrana yazdırınız.

In [1]:
with open ("example1.txt", "r") as f:
    satir = f.readlines()
    for i in satir[0:5]:
        print(i)

ascas

asdasd

sadsada

sadsadas

asdsadas

### SoruXXX
Ad, soyad,cinsiyet ve yaş alanlarından oluşan Person(kisi) adında bir sınıf oluşturunuz.

### Soru XXX
Person sınıfını kalıtım alan ve maaş, şirket, departman, ülke alanlarını da içeren Employee(Calisan) adında yeni bir sınıf oluşturunuz.

### Soru XXX
tempData.txt dosyasının ilk satırındaki verileri, oluşturduğunuz Person sınıfından bir nesne oluşturup onun içerisindeki ilgili alanlara yerleştiriniz.

### Soru XXX
tempData.txt dosyasındaki tüm verileri Person sınıfının nesnelerinden oluşan bir listede tutunuz. Sonrasında oluşturduğunuz liste üzerinde aşağıdaki işlemleri yapınız.
- Sorun çıkarmaması için her satırdaki '\n' karakterini '' ile replace ediniz. (line.replace('\n',''))
- Adı 'A' ile başlayanları ekrana yazdırınız.
- Adı 'A' ile soyadı ise 'S' ile başlayanları ekrana yazdırınız.
- Yaşı 30'dan büyük olanları ekrana yazdırınız.
- Yaşı 40'tan büyük ve 50'den küçük olanları ekrana yazdırınız.
- 'Research and Development' departmanında çalışanları ekrana yazdırınız.
- 'India'da yaşayanları ekrana yazdırınız.
- 'San Marino'da yaşayıp 'Sales' departmanında çalışanları ekrana yazdırınız.
- 'Sales' departmanında çalışıp maaşı 30000'den yüksek olanları ekrana yazdırınız.
- 'Apple Inc.' şirketinde çalışıp cinsiyeti kadın olanları ekrana yazdırınız.
- 'Apple Inc.' şirketinde çalışıp maaşı 30000'den az olanları ekrana yazdırınız.
- 'Sales' departmanında çalışanların oranını ekrana yazdırınız.
- 'IT' departmanında çalışanların oranını yazdırınız.
- 'IT' departmanında çalışan ve cinsiyeti kadın olanların oranını ekrana yazdırınız.
- 'IT' departmanında çalışan ve cinsiyeti kadın olanların, 'IT' departmanında çalışan ve cinsiyeti erkek olaranlara oranını ekrana yazdırınız.